# -*- coding: utf-8 -*-
"""Homework2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qU-LkGOW3-qgyQvUNKvdDWIEducLwxg
"""

# ShreeRama Jayanth
# 801239262
# Homework 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/IntroToML/Housing.csv'
df = pd.read_csv(file_path)

binary_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating',
               'airconditioning', 'prefarea']
df[binary_cols] = df[binary_cols].apply(lambda col: col.map({'yes': 1, 'no': 0}))

print(df.head())

np.random.seed(42)
m_total = len(df)
shuffled_idx = np.random.permutation(m_total)
train_size = int(0.8 * m_total)
train_idx = shuffled_idx[:train_size]
val_idx = shuffled_idx[train_size:]

print(f'Training rows: {len(train_idx)}, Validation rows: {len(val_idx)}')

def add_bias(X):
    return np.hstack((np.ones((X.shape[0], 1)), X))


def compute_loss(X, y, theta):
    m = len(y)
    errors = X.dot(theta) - y
    return (1 / m) * np.sum(np.square(errors))


def train_gradient_descent(X_train, y_train, X_val, y_val, alpha, iterations, reg_lambda=0.0):
    m = len(y_train)
    theta = np.zeros((X_train.shape[1], 1))
    train_losses = []
    val_losses = []

    for i in range(iterations):
        errors = X_train.dot(theta) - y_train
        gradients = (2 / m) * X_train.T.dot(errors)

        if reg_lambda > 0:
            theta_penalized = theta.copy()
            theta_penalized[0, 0] = 0
            gradients = gradients + (2 * reg_lambda / m) * theta_penalized

        theta = theta - alpha * gradients

        train_losses.append(compute_loss(X_train, y_train, theta))
        val_losses.append(compute_loss(X_val, y_val, theta))

    return theta, train_losses, val_losses


def plot_train_val_loss(train_losses, val_losses, title, yscale='linear'):
    plt.figure(figsize=(8, 5))
    plt.plot(train_losses, label='Training Loss')
    plt.plot(val_losses, label='Validation Loss')
    plt.xlabel('Iteration')
    plt.ylabel('Mean Squared Error')
    plt.yscale(yscale)
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.show()

target_col = 'price'
features_a = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking']
features_b = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom',
              'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea']

y_train = df[target_col].values[train_idx].reshape(-1, 1).astype(float)
y_val   = df[target_col].values[val_idx].reshape(-1, 1).astype(float)

learning_rates = [0.1, 0.05, 0.01]
iterations_scaled = 2000
iterations_raw = 15

X_train_1a = df[features_a].values[train_idx].astype(float)
X_val_1a   = df[features_a].values[val_idx].astype(float)

Xb_train_1a = add_bias(X_train_1a)
Xb_val_1a   = add_bias(X_val_1a)

results_1a = {}
with np.errstate(all='ignore'):
    for alpha in learning_rates:
        theta, train_losses, val_losses = train_gradient_descent(
            Xb_train_1a, y_train, Xb_val_1a, y_val, alpha, iterations_raw)
        results_1a[alpha] = (theta, train_losses, val_losses)
        print(f'alpha={alpha:<5} final train loss={train_losses[-1]:.4e}  '
              f'final val loss={val_losses[-1]:.4e}')

theta_1a, train_losses_1a, val_losses_1a = results_1a[0.1]
plot_train_val_loss(train_losses_1a, val_losses_1a,
                     'Problem 1a: Unscaled Features (alpha=0.1) - Diverges',
                     yscale='log')

X_train_1b = df[features_b].values[train_idx].astype(float)
X_val_1b   = df[features_b].values[val_idx].astype(float)

Xb_train_1b = add_bias(X_train_1b)
Xb_val_1b   = add_bias(X_val_1b)

results_1b = {}
with np.errstate(all='ignore'):
    for alpha in learning_rates:
        theta, train_losses, val_losses = train_gradient_descent(
            Xb_train_1b, y_train, Xb_val_1b, y_val, alpha, iterations_raw)
        results_1b[alpha] = (theta, train_losses, val_losses)
        print(f'alpha={alpha:<5} final train loss={train_losses[-1]:.4e}  '
              f'final val loss={val_losses[-1]:.4e}')

theta_1b, train_losses_1b, val_losses_1b = results_1b[0.1]
plot_train_val_loss(train_losses_1b, val_losses_1b,
                     'Problem 1b: Unscaled Features, 11 inputs (alpha=0.1) - Diverges',
                     yscale='log')

def run_scaled_experiment(features, scaler_class, alpha, iterations):
    X_train = df[features].values[train_idx].astype(float)
    X_val   = df[features].values[val_idx].astype(float)

    scaler = scaler_class().fit(X_train)
    Xs_train = scaler.transform(X_train)
    Xs_val   = scaler.transform(X_val)

    Xb_train = add_bias(Xs_train)
    Xb_val   = add_bias(Xs_val)

    theta, train_losses, val_losses = train_gradient_descent(
        Xb_train, y_train, Xb_val, y_val, alpha, iterations)
    return theta, train_losses, val_losses

results_2a_std = {}
results_2a_norm = {}
for alpha in learning_rates:
    results_2a_std[alpha] = run_scaled_experiment(features_a, StandardScaler, alpha, iterations_scaled)
    results_2a_norm[alpha] = run_scaled_experiment(features_a, MinMaxScaler, alpha, iterations_scaled)
    print(f'alpha={alpha:<5} '
          f'standardized final: train={results_2a_std[alpha][1][-1]:.4e} val={results_2a_std[alpha][2][-1]:.4e}  |  '
          f'normalized final: train={results_2a_norm[alpha][1][-1]:.4e} val={results_2a_norm[alpha][2][-1]:.4e}')

best_alpha_2a_std = min(results_2a_std, key=lambda a: results_2a_std[a][2][-1])
best_alpha_2a_norm = min(results_2a_norm, key=lambda a: results_2a_norm[a][2][-1])

theta_2a_std, tl_2a_std, vl_2a_std = results_2a_std[best_alpha_2a_std]
theta_2a_norm, tl_2a_norm, vl_2a_norm = results_2a_norm[best_alpha_2a_norm]

plot_train_val_loss(tl_2a_std, vl_2a_std,
                     f'Problem 2a: Standardized Inputs (alpha={best_alpha_2a_std})')
plot_train_val_loss(tl_2a_norm, vl_2a_norm,
                     f'Problem 2a: Normalized Inputs (alpha={best_alpha_2a_norm})')

results_2b_std = {}
results_2b_norm = {}
for alpha in learning_rates:
    results_2b_std[alpha] = run_scaled_experiment(features_b, StandardScaler, alpha, iterations_scaled)
    results_2b_norm[alpha] = run_scaled_experiment(features_b, MinMaxScaler, alpha, iterations_scaled)
    print(f'alpha={alpha:<5} '
          f'standardized final: train={results_2b_std[alpha][1][-1]:.4e} val={results_2b_std[alpha][2][-1]:.4e}  |  '
          f'normalized final: train={results_2b_norm[alpha][1][-1]:.4e} val={results_2b_norm[alpha][2][-1]:.4e}')

best_alpha_2b_std = min(results_2b_std, key=lambda a: results_2b_std[a][2][-1])
best_alpha_2b_norm = min(results_2b_norm, key=lambda a: results_2b_norm[a][2][-1])

theta_2b_std, tl_2b_std, vl_2b_std = results_2b_std[best_alpha_2b_std]
theta_2b_norm, tl_2b_norm, vl_2b_norm = results_2b_norm[best_alpha_2b_norm]

plot_train_val_loss(tl_2b_std, vl_2b_std,
                     f'Problem 2b: Standardized Inputs, 11 features (alpha={best_alpha_2b_std})')
plot_train_val_loss(tl_2b_norm, vl_2b_norm,
                     f'Problem 2b: Normalized Inputs, 11 features (alpha={best_alpha_2b_norm})')

best_scaler_a = StandardScaler if vl_2a_std[-1] <= vl_2a_norm[-1] else MinMaxScaler
best_alpha_3a = best_alpha_2a_std if best_scaler_a is StandardScaler else best_alpha_2a_norm
print('Best scaling approach for feature set (a):', best_scaler_a.__name__)

X_train_3a = df[features_a].values[train_idx].astype(float)
X_val_3a   = df[features_a].values[val_idx].astype(float)
scaler_3a = best_scaler_a().fit(X_train_3a)
Xb_train_3a = add_bias(scaler_3a.transform(X_train_3a))
Xb_val_3a   = add_bias(scaler_3a.transform(X_val_3a))

reg_lambdas = [0, 1, 10, 100]
results_3a = {}
for lam in reg_lambdas:
    theta, train_losses, val_losses = train_gradient_descent(
        Xb_train_3a, y_train, Xb_val_3a, y_val, best_alpha_3a, iterations_scaled, reg_lambda=lam)
    results_3a[lam] = (theta, train_losses, val_losses)
    print(f'lambda={lam:<5} final train loss={train_losses[-1]:.4e}  final val loss={val_losses[-1]:.4e}')

best_lambda_3a = min(results_3a, key=lambda l: results_3a[l][2][-1])
theta_3a, tl_3a, vl_3a = results_3a[best_lambda_3a]
print('Best lambda:', best_lambda_3a)

plot_train_val_loss(tl_3a, vl_3a,
                     f'Problem 3a: Ridge Penalty, lambda={best_lambda_3a} (best scaling from 2a)')

best_scaler_b = StandardScaler if vl_2b_std[-1] <= vl_2b_norm[-1] else MinMaxScaler
best_alpha_3b = best_alpha_2b_std if best_scaler_b is StandardScaler else best_alpha_2b_norm
print('Best scaling approach for feature set (b):', best_scaler_b.__name__)

X_train_3b = df[features_b].values[train_idx].astype(float)
X_val_3b   = df[features_b].values[val_idx].astype(float)
scaler_3b = best_scaler_b().fit(X_train_3b)
Xb_train_3b = add_bias(scaler_3b.transform(X_train_3b))
Xb_val_3b   = add_bias(scaler_3b.transform(X_val_3b))

results_3b = {}
for lam in reg_lambdas:
    theta, train_losses, val_losses = train_gradient_descent(
        Xb_train_3b, y_train, Xb_val_3b, y_val, best_alpha_3b, iterations_scaled, reg_lambda=lam)
    results_3b[lam] = (theta, train_losses, val_losses)
    print(f'lambda={lam:<5} final train loss={train_losses[-1]:.4e}  final val loss={val_losses[-1]:.4e}')

best_lambda_3b = min(results_3b, key=lambda l: results_3b[l][2][-1])
theta_3b, tl_3b, vl_3b = results_3b[best_lambda_3b]
print('Best lambda:', best_lambda_3b)

plot_train_val_loss(tl_3b, vl_3b,
                     f'Problem 3b: Ridge Penalty, lambda={best_lambda_3b} (best scaling from 2b)')