# -*- coding: utf-8 -*-
"""Homework3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DZbXxjTse8996M1te8F0I1Jz9xg-gQE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')
import warnings

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (confusion_matrix, accuracy_score, precision_score,
                              recall_score, f1_score, log_loss)

def train_test_split_and_scale(X, y, test_size=0.2, random_state=0):
    """80/20 split (or as specified) + StandardScaler, fit on the training set only."""
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y)

    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train, X_test, y_train, y_test


def train_logistic_regression(X_train, y_train, iterations=200, penalty='l2', C=1.0):
    """
    Train sklearn's LogisticRegression using warm_start so we can record loss and
    accuracy after every training step (see note above on why this loop exists).
    """
    classifier = LogisticRegression(warm_start=True, max_iter=1, solver='lbfgs',
                                     penalty=penalty, C=C)
    train_losses = []
    train_accuracies = []

    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        for i in range(iterations):
            classifier.fit(X_train, y_train)
            probs = classifier.predict_proba(X_train)
            preds = classifier.predict(X_train)
            train_losses.append(log_loss(y_train, probs))
            train_accuracies.append(accuracy_score(y_train, preds))

    return classifier, train_losses, train_accuracies


def evaluate_classifier(classifier, X_test, y_test):
    """Confusion matrix + accuracy, precision, recall, F1 on the held-out test set."""
    y_pred = classifier.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    results = {
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred),
        'recall': recall_score(y_test, y_pred),
        'f1': f1_score(y_test, y_pred)
    }
    return cm, results


def plot_loss_and_accuracy(train_losses, train_accuracies, title_suffix=''):
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

    axes[0].plot(train_losses, color='blue')
    axes[0].set_xlabel('Iteration')
    axes[0].set_ylabel('Training Loss (log loss)')
    axes[0].set_title(f'Training Loss over Iterations {title_suffix}')
    axes[0].grid(True)

    axes[1].plot(train_accuracies, color='green')
    axes[1].set_xlabel('Iteration')
    axes[1].set_ylabel('Training Accuracy')
    axes[1].set_title(f'Training Accuracy over Iterations {title_suffix}')
    axes[1].grid(True)

    plt.tight_layout()
    plt.show()


def plot_confusion_matrix(cm, title_suffix=''):
    class_names = [0, 1]
    fig, ax = plt.subplots()
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names)
    plt.yticks(tick_marks, class_names)
    sns.heatmap(pd.DataFrame(cm), annot=True, cmap='YlGnBu', fmt='g')
    ax.xaxis.set_label_position('top')
    plt.tight_layout()
    plt.title(f'Confusion Matrix {title_suffix}', y=1.1)
    plt.ylabel('Actual label')
    plt.xlabel('Predicted label')
    plt.show()


def print_results(results, title_suffix=''):
    print(f'Results {title_suffix}')
    print(f"  Accuracy:  {results['accuracy']:.4f}")
    print(f"  Precision: {results['precision']:.4f}")
    print(f"  Recall:    {results['recall']:.4f}")
    print(f"  F1 Score:  {results['f1']:.4f}")

diabetes_file_path = '/content/drive/My Drive/IntroToML/diabetes.csv'
diabetes_df = pd.read_csv(diabetes_file_path)
print(diabetes_df.head())
print(diabetes_df.shape)

X_diabetes = diabetes_df.drop(columns=['Outcome']).values
y_diabetes = diabetes_df['Outcome'].values

X_train_d, X_test_d, y_train_d, y_test_d = train_test_split_and_scale(X_diabetes, y_diabetes)
print(f'Training rows: {len(y_train_d)}, Test rows: {len(y_test_d)}')

clf_diabetes, train_losses_d, train_acc_d = train_logistic_regression(X_train_d, y_train_d)
plot_loss_and_accuracy(train_losses_d, train_acc_d, '(Diabetes)')

cm_diabetes, results_diabetes = evaluate_classifier(clf_diabetes, X_test_d, y_test_d)
print_results(results_diabetes, '(Diabetes - Test Set)')
plot_confusion_matrix(cm_diabetes, '(Diabetes)')

cancer_file_path = '/content/drive/My Drive/IntroToML/Cancer.csv'
cancer_df = pd.read_csv(cancer_file_path)
cancer_df = cancer_df.drop(columns=['id'])
cancer_df = cancer_df.loc[:, ~cancer_df.columns.str.contains('^Unnamed')]
cancer_df['diagnosis'] = cancer_df['diagnosis'].map({'M': 1, 'B': 0})
print(cancer_df.head())
print(cancer_df.shape)

X_cancer = cancer_df.drop(columns=['diagnosis']).values
y_cancer = cancer_df['diagnosis'].values

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split_and_scale(X_cancer, y_cancer)
print(f'Training rows: {len(y_train_c)}, Test rows: {len(y_test_c)}')

clf_cancer_nopen, train_losses_c1, train_acc_c1 = train_logistic_regression(
    X_train_c, y_train_c, penalty=None)
plot_loss_and_accuracy(train_losses_c1, train_acc_c1, '(Cancer - No Penalty)')

cm_cancer1, results_cancer1 = evaluate_classifier(clf_cancer_nopen, X_test_c, y_test_c)
print_results(results_cancer1, '(Cancer - No Penalty - Test Set)')
plot_confusion_matrix(cm_cancer1, '(Cancer - No Penalty)')

clf_cancer_l2, train_losses_c2, train_acc_c2 = train_logistic_regression(
    X_train_c, y_train_c, penalty='l2', C=1.0)
plot_loss_and_accuracy(train_losses_c2, train_acc_c2, '(Cancer - L2 Penalty)')

cm_cancer2, results_cancer2 = evaluate_classifier(clf_cancer_l2, X_test_c, y_test_c)
print_results(results_cancer2, '(Cancer - L2 Penalty - Test Set)')
plot_confusion_matrix(cm_cancer2, '(Cancer - L2 Penalty)')

comparison = pd.DataFrame({
    'No Penalty': results_cancer1,
    'L2 Penalty': results_cancer2
})
print(comparison)